### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by bitacovir** [wassimj/TopologicST#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://wassimj-topologicst-plotly-test01-yul95o.streamlitapp.com/wassimj/topologicst/main/plotly-test01.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by wassimj** [comment]
Thanks. Yes, I am on a free tier. All of this is just for testing.
